name: Restore artifacts

description: |
  When no input is given, artifacts are restored in the current directory, under their artifact `name`.

  This composite restore all of our artifacts, at their right path.

inputs:
  type:
    description: Type of artifacts to restore (`all` | `specs` | `js_utils`)
    required: false
  php:
    description: Whether this job ran or not
    required: false
  java:
    description: Whether this job ran or not
    required: false
  javascript:
    description: Whether this job ran or not
    required: false

runs:
  using: composite
  steps:
    # Bundled specs
    - name: specs
      if: ${{ inputs.type == 'all' || inputs.type == 'specs' }}
      uses: actions/download-artifact@v3
      with:
        name: specs
        path: specs/bundled/

    # JavaScript utils
    - name: client-javascript-utils-client-common
      if: ${{ (inputs.javascript == 'true' && inputs.type == 'all') || inputs.type == 'js_utils' }}
      uses: actions/download-artifact@v3
      with:
        name: client-javascript-utils-client-common
        path: clients/algoliasearch-client-javascript/packages/client-common/

    - name: client-javascript-utils-requester-browser-xhr
      if: ${{ (inputs.javascript == 'true' && inputs.type == 'all') || inputs.type == 'js_utils' }}
      uses: actions/download-artifact@v3
      with:
        name: client-javascript-utils-requester-browser-xhr
        path: clients/algoliasearch-client-javascript/packages/requester-browser-xhr/

    - name: client-javascript-utils-requester-node-http
      if: ${{ (inputs.javascript == 'true' && inputs.type == 'all') || inputs.type == 'js_utils' }}
      uses: actions/download-artifact@v3
      with:
        name: client-javascript-utils-requester-node-http
        path: clients/algoliasearch-client-javascript/packages/requester-node-http/

    # Clients and tests
    - name: Download clients and tests artifacts
      if: ${{ inputs.type == 'all' }}
      shell: bash
      run: |
        echo "Downloading test artifact"
        gh api -H "Accept: application/vnd.github.v3+json" \
          /repos/algolia/api-clients-automation/actions/artifacts/clients-java/zip
