name: Restore artifacts

description: |
  When no input is given, artifacts are restored in the current directory, under their artifact `name`.

  This composite restore all of our artifacts, at their right path.

inputs:
  type:
    description: Type of artifacts to restore (`all` | `specs` | `js_utils`)
    required: false
  matrix:
    description: The matrix of language clients to download
    required: false
  token:
    description: GITHUB_TOKEN from secrets (not accessible from here)
    required: false

runs:
  using: composite
  steps:
    - name: Download clients-java artifact
      if: ${{ inputs.java == 'true' && inputs.type == 'all' }}
      uses: actions/download-artifact@v3
      with:
        name: clients-java

    # Clients and tests
    - name: Download clients and tests artifacts
      if: ${{ inputs.type == 'all' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        echo ${{ inputs.matrix }} | jq -c '.client []' | while read client; do
          language=$(jq -r '.language' <<< $client)
          artifact="clients-$language"
          echo "Downloading $artifact artifacts"

          rm -rf $(jq -r '.path' <<< $client)
          rm -rf $(jq -r '.testToDelete' <<< $client) || true

          # Get the artifact id
          id=$(gh api -H "Accept: application/vnd.github.v3+json" /repos/algolia/api-clients-automation/actions/runs/${{ github.run_id }}/artifacts -q ".artifacts [] | select(.name==\"$artifact\") | .id")
          echo "Artifact id: $id"
          gh api -H "Accept: application/vnd.github.v3+json" /repos/algolia/api-clients-automation/actions/artifacts/$id/zip > $artifact.zip
          unzip -q -o $artifact.zip && rm $artifact.zip
        done
